# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cvfl1atrtqoVhpcH9VIb-2z6RHd_grX3
"""

from google.colab import files
uploaded = files.upload()

import zipfile
import os

# Get the uploaded zip filename
zip_filename = next(iter(uploaded))

# Unzip it
with zipfile.ZipFile(zip_filename, 'r') as zip_ref:
    zip_ref.extractall()  # Extracts to the current directory

# See what files are extracted
os.listdir()

import pandas as pd
import numpy as np

# STEP 1: Load the raw dataset
df = pd.read_csv("KaggleV2-May-2016.csv")

# STEP 2: Make a copy for comparison
df_original = df.copy()

# STEP 3: Rename column headers (lowercase, no spaces)
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

# STEP 4: Identify & handle missing values
missing_values = df.isnull().sum()

# STEP 5: Remove duplicate rows
duplicates_before = df.duplicated().sum()
df.drop_duplicates(inplace=True)

# STEP 6: Standardize text values (gender)
df['gender'] = df['gender'].str.strip().str.upper()

# STEP 7: Fix invalid age values (e.g., negative age)
invalid_ages = df[df['age'] < 0].shape[0]
df = df[df['age'] >= 0]

# STEP 8: Convert date columns to dd-mm-yyyy format
df['scheduledday'] = pd.to_datetime(df['scheduledday']).dt.strftime('%d-%m-%Y')
df['appointmentday'] = pd.to_datetime(df['appointmentday']).dt.strftime('%d-%m-%Y')

# STEP 9: Fix data types if needed
df['age'] = df['age'].astype(int)
df.rename(columns={'no-show': 'no_show'}, inplace=True)

# STEP 10: Export cleaned dataset
df.to_csv("cleaned_kaggle_appointments.csv", index=False)

# STEP 11: Generate Summary
summary = {
    "Columns Renamed": df_original.columns.tolist(),
    "New Columns": df.columns.tolist(),
    "Duplicates Removed": duplicates_before,
    "Missing Values (before cleaning)": missing_values.to_dict(),
    "Invalid Ages Removed": invalid_ages,
    "Gender Values After Cleaning": df['gender'].unique().tolist(),
    "Final Shape": df.shape,
    "Date Format": "dd-mm-yyyy"
}

print("✅ Data Cleaning Completed.\n")
print("📋 Summary of Changes:")
for k, v in summary.items():
    print(f"- {k}: {v}")